### ISSUE TITLE
The link to download the weight file went wrong.

### ISSUE THREAD

**Issue by bhmaxu** [HMS-IDAC/BINDER#10]
I am unable to download files through the dropbox link in download_weights.sh. Can you provide another way, such as Google Drive?

**Comment by teddykoker** [comment]
Thank you for the issue. The weights can be downloaded from [google drive](https://drive.google.com/file/d/12jWquL2TU9J7VAo3J1vORMTf5r4PKcgv/view?usp=sharing). I have updated the readme to reflect this.
