### ISSUE TITLE
Weights download script not working

### ISSUE THREAD

**Issue by b2077** [HMS-IDAC/BINDER#4]
Hi, I think the weights download link might be expired:

HTTP request sent, awaiting response... 301 Moved Permanently
Location: /sh/dl/e53tlk0y3d6nx3u/AABFpTSipYnAUcqLUsimculTa [following]
--2021-08-23 10:42:23--  https://www.dropbox.com/sh/dl/e53tlk0y3d6nx3u/AABFpTSipYnAUcqLUsimculTa
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 400 Bad Request
2021-08-23 10:42:23 ERROR 400: Bad Request.

**Comment by teddykoker** [comment]
Hi, I have temporarily re-uploaded them to google drive here: https://drive.google.com/file/d/12jWquL2TU9J7VAo3J1vORMTf5r4PKcgv/view?usp=sharing.

@cicconet Do you think you could upload these to a permanent location on dropbox? Thanks!

**Comment by cicconet** [comment]
Thanks @teddykoker! @b2077: we have released the corresponding image dataset [https://doi.org/10.7910/DVN/9YTD9Z] -- feel free to download and train the model from scratch.
