### ISSUE TITLE
The link of weights are not avaliable

### ISSUE THREAD

**Issue by tbwxmu** [HMS-IDAC/BINDER#9]
Thanks for sharing your codes, I am interested in this research field.
It seems that we can not download the weight with the supported scritpt:  [BINDER](https://github.com/HMS-IDAC/BINDER)/[retrieval](https://github.com/HMS-IDAC/BINDER/tree/master/retrieval)/[scripts](https://github.com/HMS-IDAC/BINDER/tree/master/retrieval/scripts)/download_weights.sh

please renew it and looking forward to your reply

**Comment by cicconet** [comment]
see https://drive.google.com/file/d/12jWquL2TU9J7VAo3J1vORMTf5r4PKcgv/view?usp=sharing
